describe('test filter by type', () => {
    it('tests if filter by type and booking is working', () => {
        cy.visit('https://sebastianpiresmolin.github.io/esc-group-project/')
        cy.contains('Play online').click()
        cy.wait(200)
        cy.url().should('include', '/challenges.html')
        cy.get('.filterButton').click()
        cy.wait(200)
        cy.get('#online').uncheck()
        cy.wait(200)
        cy.contains('button', 'Book this room').click({force: true}) 
        cy.contains('Search available times').click()
        cy.get('.input__name').type('Antonis Terzo')
        cy.get('.input__mail').type('tralala')
        cy.wait(200)
        cy.get('.button__submit').click()
        cy.get('.error__msg').should('have.text', 'You must enter a valid email!')
        cy.get('.input__mail').clear().type('example@gmail.com')
        cy.wait(200)
        cy.get('.button__submit').click()
        cy.get('input[type="tel"]').type('0730234580')
        cy.get('.modal__participants').click().next().select(1).should('have.value', '2 participants')
        cy.wait(200)
        cy.get('.button__submit').click()
        cy.contains('Close window').click()
    })
})
