describe('test filter by type', () => {
    it('tests if filter by type is working', () => {
        cy.visit('https://sebastianpiresmolin.github.io/esc-group-project/')
        cy.contains('Play online').click()
        cy.wait(250)
        cy.url().should('include', '/challenges.html')
        cy.get('.filterButton').click()
        cy.wait(250)
        cy.get('#online').uncheck()
        cy.wait(250)
        cy.contains('Book this room').click()
        cy.wait(250)
        cy.contains('Search available times').click()
        cy.get('.input__name').type('Antonis Terzo')
        cy.wait(250)
        cy.get('.input__mail').type('tralala')
        cy.wait(250)
        cy.get('.button__submit').click()
        cy.wait(250)
    })
})